name: IcShop
main: lucia\IcShop\IcShop
author: lucia, NLOG
api: [3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7]
version: 1.6.1-alpha

commands:
 상점:
  permission: icshop.command.shop
  description: 상점 관리 커맨드
 판매:
  permission: icshop.command.sell
  description: 아이템 판매 커맨드
 구매:
  permission: icshop.command.buy
  description: 아이템 구매 커맨드
  
permissions:
 icshop.command.buy:
  default: true
 icshop.command.sell:
  default: true
 icshop.command.shop:
  default: OP
